/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'replies' : Array<bigint>,
  'parentId' : [] | [bigint],
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface NftPost {
  'id' : bigint,
  'metadata' : PostMetadata,
  'author' : Principal,
  'timestamp' : Time,
  'comments' : Array<bigint>,
  'images' : Array<ExternalBlob>,
}
export interface PostMetadata {
  'description' : string,
  'author' : [] | [Principal],
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNftPost' : ActorMethod<[PostMetadata, Array<ExternalBlob>], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllPosts' : ActorMethod<[], Array<[bigint, NftPost]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComment' : ActorMethod<[bigint], [] | [Comment]>,
  'getFollowers' : ActorMethod<[], Array<UserId>>,
  'getFollowing' : ActorMethod<[], Array<UserId>>,
  'getPost' : ActorMethod<[bigint], [] | [NftPost]>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getPostLikes' : ActorMethod<[bigint], bigint>,
  'getUserPosts' : ActorMethod<[Principal], Array<NftPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserLiked' : ActorMethod<[bigint, Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmpty' : ActorMethod<[string], boolean>,
  'isFollowingUser' : ActorMethod<[UserId], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];