/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostMetadata = IDL.Record({
  'description' : IDL.Text,
  'author' : IDL.Opt(IDL.Principal),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const NftPost = IDL.Record({
  'id' : IDL.Nat,
  'metadata' : PostMetadata,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'comments' : IDL.Vec(IDL.Nat),
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'replies' : IDL.Vec(IDL.Nat),
  'parentId' : IDL.Opt(IDL.Nat),
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNftPost' : IDL.Func(
      [PostMetadata, IDL.Vec(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAllPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, NftPost))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComment' : IDL.Func([IDL.Nat], [IDL.Opt(Comment)], ['query']),
  'getFollowers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(NftPost)], ['query']),
  'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(NftPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserLiked' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmpty' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostMetadata = IDL.Record({
    'description' : IDL.Text,
    'author' : IDL.Opt(IDL.Principal),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const NftPost = IDL.Record({
    'id' : IDL.Nat,
    'metadata' : PostMetadata,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'comments' : IDL.Vec(IDL.Nat),
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'replies' : IDL.Vec(IDL.Nat),
    'parentId' : IDL.Opt(IDL.Nat),
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNftPost' : IDL.Func(
        [PostMetadata, IDL.Vec(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAllPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, NftPost))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComment' : IDL.Func([IDL.Nat], [IDL.Opt(Comment)], ['query']),
    'getFollowers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(NftPost)], ['query']),
    'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(NftPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserLiked' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmpty' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };